xle_cafe:
    resource: "@XleCafeBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type:     annotation
    prefix:   /{_locale}/app
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%'

