<?php

namespace Xle\CafeBundle\Repository;

/**
 * CafeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CafeRepository extends \Doctrine\ORM\EntityRepository
{
}
