cmanager_index:
    path:     /
    defaults: { _controller: "XleCafeBundle:Cafe:index" }
    methods:  GET

cmanager_list:
    path:     /list
    defaults: { _controller: "XleCafeBundle:Cafe:list" }
    methods:  GET

cmanager_info:
    path:     /{cafe_id}/info
    defaults: { _controller: "XleCafeBundle:Cafe:info" }
    methods:  POST

cmanager_info1:
    path:     /{cafe_id}/info1
    defaults: { _controller: "XleCafeBundle:Cafe:info1" }
    methods:  [GET, POST]

cmanager_modify:
    path:     /modify
    defaults: { _controller: "XleCafeBundle:Cafe:modify" }
    methods:  POST

cmanager_show:
    path:     /{id}/show
    defaults: { _controller: "XleCafeBundle:Cafe:show" }
    methods:  GET

cmanager_new:
    path:     /new
    defaults: { _controller: "XleCafeBundle:Cafe:new" }
    methods:  [GET, POST]

cmanager_edit:
    path:     /{id}/edit
    defaults: { _controller: "XleCafeBundle:Cafe:edit" }
    methods:  [GET, POST]

cmanager_delete:
    path:     /{id}/delete
    defaults: { _controller: "XleCafeBundle:Cafe:delete" }
    methods:  DELETE
