xle_cafe_cmanager:
    resource: "@XleCafeBundle/Resources/config/routing/cafe.yml"
    prefix:   /cmanager

xle_cafe_homepage:
    path:     /
    defaults: { _controller: XleCafeBundle:Default:index }
